title: timm lua
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
