name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.4"
    - uses: leafo/gh-actions-luarocks@v2
    - name: test
      run: |
        cd src; lua about.lua -g all
